[package]
name = "yagababble"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Woolhouse"]
description = "A simple gibberish word generator using markov chains"
license = "MIT"


[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
unicode-segmentation = "1.12.0"
